apiVersion: v1
kind: PersistentVolume
metadata:
  name: exercise-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/tmp/data"